all_attrs_names = [
    "https://smartdatamodels.org/address",
    "https://smartdatamodels.org/dataProvider",
    "https://smartdatamodels.org/source",
    "https://uri.etsi.org/ngsi-ld/default-context/stationName",
    "location",
    "https://smartdatamodels.org/dateObserved",
    "https://smartdatamodels.org/dataModel.Weather/temperature",
    "https://uri.etsi.org/ngsi-ld/default-context/temperatureUnit",
    "https://smartdatamodels.org/dataModel.Weather/windSpeed",
    "https://uri.etsi.org/ngsi-ld/default-context/windSpeedUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/beaufort",
    "https://uri.etsi.org/ngsi-ld/default-context/beaufortUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/humidity",
    "https://uri.etsi.org/ngsi-ld/default-context/humidityUnit",
    "https://smartdatamodels.org/dataModel.Weather/atmosphericPressure",
    "https://uri.etsi.org/ngsi-ld/default-context/atmosphericPressureUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/highestDailyTemperature",
    "https://uri.etsi.org/ngsi-ld/default-context/highestDailyTemperatureUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/lowestDailyTemperature",
    "https://uri.etsi.org/ngsi-ld/default-context/lowestDailyTemperatureUnit",
    "https://smartdatamodels.org/dataModel.Weather/precipitation",
    "https://uri.etsi.org/ngsi-ld/default-context/precipitationUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/highestDailyGust",
    "https://uri.etsi.org/ngsi-ld/default-context/highestDailyGustUnit"
]

useful_attrs_names = [
    # "https://smartdatamodels.org/address",
    # "https://smartdatamodels.org/dataProvider",
    # "https://smartdatamodels.org/source",
    "https://uri.etsi.org/ngsi-ld/default-context/stationName",
    "location",
    "https://smartdatamodels.org/dateObserved",
    "https://smartdatamodels.org/dataModel.Weather/temperature",
    # "https://uri.etsi.org/ngsi-ld/default-context/temperatureUnit",
    "https://smartdatamodels.org/dataModel.Weather/windSpeed",
    # "https://uri.etsi.org/ngsi-ld/default-context/windSpeedUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/beaufort",
    # "https://uri.etsi.org/ngsi-ld/default-context/beaufortUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/humidity",
    # "https://uri.etsi.org/ngsi-ld/default-context/humidityUnit",
    "https://smartdatamodels.org/dataModel.Weather/atmosphericPressure",
    # "https://uri.etsi.org/ngsi-ld/default-context/atmosphericPressureUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/highestDailyTemperature",
    # "https://uri.etsi.org/ngsi-ld/default-context/highestDailyTemperatureUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/lowestDailyTemperature",
    # "https://uri.etsi.org/ngsi-ld/default-context/lowestDailyTemperatureUnit",
    "https://smartdatamodels.org/dataModel.Weather/precipitation",
    # "https://uri.etsi.org/ngsi-ld/default-context/precipitationUnit",
    "https://uri.etsi.org/ngsi-ld/default-context/highestDailyGust",
    # "https://uri.etsi.org/ngsi-ld/default-context/highestDailyGustUnit"
]

short_useful_attrs_names = [
    # "address",
    # "dataProvider",
    # "source",
    "stationName",
    "location",
    "dateObserved",
    "temperature",
    # "temperatureUnit",
    "windSpeed",
    # "windSpeedUnit",
    "beaufort",
    # "beaufortUnit",
    "humidity",
    # "humidityUnit",
    "atmosphericPressure",
    # "atmosphericPressureUnit",
    "highestDailyTemperature",
    # "highestDailyTemperatureUnit",
    "lowestDailyTemperature",
    # "lowestDailyTemperatureUnit",
    "precipitation",
    # "precipitationUnit",
    "highestDailyGust",
    # "highestDailyGustUnit"
]
